export const data = {
  emptyData: [
    {
      id: 0,
      weight: 0,
      date: null,
      week: 0,
      type: null,
    },
    {
      id: 1,
      weight: 0,
      date: null,
      week: 1,
    },
    {
      id: 2,
      weight: 0,
      date: null,
      week: 2,
      type: null,
    },
    {
      id: 3,
      weight: 0,
      date: null,
      week: 3,
      type: null,
    },
    {
      id: 4,
      weight: 0,
      date: null,
      week: 4,
      type: null,
    },
    {
      id: 5,
      weight: 0,
      date: null,
      week: 5,
      type: null,
    },
    {
      id: 6,
      weight: 0,
      date: null,
      week: 6,
      type: null,
    },
    {
      id: 7,
      weight: 0,
      date: null,
      week: 7,
      type: null,
    },
  ],
  benchPress: [
    {
      id: 0,
      weight: 0,
      date: null,
      week: 0,
      type: "filler",
    },
    {
      id: 1,
      weight: 135,
      date: "2020-05-05",
      week: 1,
      type: "benchPress",
    },
    {
      id: 2,
      weight: 155,
      date: "2020-05-10",
      week: 2,
      type: "benchPress",
    },
    {
      id: 3,
      weight: 185,
      date: "2020-05-15",
      week: 3,
      type: "benchPress",
    },
    {
      id: 4,
      weight: 195,
      date: "2020-05-20",
      week: 4,
      type: "benchPress",
    },
    {
      id: 5,
      weight: 195,
      date: "2020-05-25",
      week: 5,
      type: "filler",
    },
    {
      id: 6,
      weight: 205,
      date: "2020-05-30",
      week: 6,
      type: "benchPress",
    },
    {
      id: 7,
      weight: 225,
      date: "2020-06-05",
      week: 7,
      type: "benchPress",
    },
    {
      id: 8,
      weight: 225,
      date: null,
      week: 8,
      type: "filler",
    },
  ],
  deadlift: [
    {
      id: 0,
      weight: 0,
      date: null,
      week: 0,
      type: "filler",
    },
    {
      id: 1,
      weight: 225,
      date: "2020-05-05",
      week: 1,
      type: "deadlift",
    },
    {
      id: 2,
      weight: 245,
      date: "2020-05-10",
      week: 2,
      type: "deadlift",
    },
    {
      id: 3,
      weight: 285,
      date: "2020-05-15",
      week: 3,
      type: "deadlift",
    },
    {
      id: 4,
      weight: 305,
      date: "2020-05-20",
      week: 4,
      type: "deadlift",
    },
    {
      id: 5,
      weight: 315,
      date: "2020-05-25",
      week: 5,
      type: "filler",
    },
    {
      id: 6,
      weight: 325,
      date: "2020-05-30",
      week: 6,
      type: "deadlift",
    },
    {
      id: 7,
      weight: 335,
      date: "2020-06-05",
      week: 7,
      type: "deadlift",
    },
    {
      id: 8,
      weight: 335,
      date: null,
      week: 8,
      type: "filler",
    },
  ],
  overheadPress: [
    {
      id: 0,
      weight: 0,
      date: null,
      week: 0,
      type: "filler",
    },
    {
      id: 1,
      weight: 95,
      date: "2020-05-05",
      week: 1,
      type: "overheadPress",
    },
    {
      id: 2,
      weight: 95,
      date: "2020-05-10",
      week: 2,
      type: "overheadPress",
    },
    {
      id: 3,
      weight: 105,
      date: "2020-05-15",
      week: 3,
      type: "overheadPress",
    },
    {
      id: 4,
      weight: 115,
      date: "2020-05-20",
      week: 4,
      type: "overheadPress",
    },
    {
      id: 5,
      weight: 125,
      date: "2020-05-25",
      week: 5,
      type: "overheadPress",
    },
    {
      id: 6,
      weight: 135,
      date: "2020-05-30",
      week: 6,
      type: "overheadPress",
    },
    {
      id: 7,
      weight: 135,
      date: "2020-06-05",
      week: 7,
      type: "overheadPress",
    },
    {
      id: 8,
      weight: 135,
      date: null,
      week: 8,
      type: "filler",
    },
  ],
  squat: [
    {
      id: 0,
      weight: 0,
      date: null,
      week: 0,
      type: "filler",
    },
    {
      id: 1,
      weight: 225,
      date: "2020-05-05",
      week: 1,
      type: "squat",
    },
    {
      id: 2,
      weight: 255,
      date: "2020-05-10",
      week: 2,
      type: "squat",
    },
    {
      id: 3,
      weight: 285,
      date: "2020-05-15",
      week: 3,
      type: "squat",
    },
    {
      id: 4,
      weight: 295,
      date: "2020-05-20",
      week: 4,
      type: "squat",
    },
    {
      id: 5,
      weight: 305,
      date: "2020-05-25",
      week: 5,
      type: "squat",
    },
    {
      id: 6,
      weight: 315,
      date: "2020-05-30",
      week: 6,
      type: "squat",
    },
    {
      id: 7,
      weight: 325,
      date: "2020-06-05",
      week: 7,
      type: "squat",
    },
    {
      id: 8,
      weight: 325,
      date: null,
      week: 8,
      type: "filler",
    },
  ],
};
