export const data = {
  emptyData: [
    {
      id: 1,
      weight: 0,
      date: null,
      week: 1,
    },
    {
      id: 2,
      weight: 0,
      date: null,
      week: 2,
      type: null,
    },
    {
      id: 3,
      weight: 0,
      date: null,
      week: 3,
      type: null,
    },
    {
      id: 4,
      weight: 0,
      date: null,
      week: 4,
      type: null,
    },
    {
      id: 5,
      weight: 0,
      date: null,
      week: 5,
      type: null,
    },
    {
      id: 6,
      weight: 0,
      date: null,
      week: 6,
      type: null,
    },
  ],
  setData: [
    {
      set: "SET 1",
      lbs: "165",
      reps: "8",
    },
    {
      set: "SET 2",
      lbs: "190",
      reps: "6",
    },
    {
      set: "SET 3",
      lbs: "215",
      reps: "4",
    },
    {
      set: "SET 4",
      lbs: "215",
      reps: "4",
    },
    {
      set: "SET 5",
      lbs: "215",
      reps: "4",
    },
    {
      set: "SET 6",
      lbs: "200",
      reps: "5",
    },
    {
      set: "SET 7",
      lbs: "190",
      reps: "6",
    },
    {
      set: "SET 8",
      lbs: "175",
      reps: "7",
    },
    {
      set: "SET 9",
      lbs: "165+",
      reps: "8",
    },
  ],
  benchPress: [
    {
      id: 1,
      weight: 135,
      date: "2020-05-05",
      week: 1,
      type: "benchPress",
    },
    {
      id: 2,
      weight: 155,
      date: "2020-05-10",
      week: 2,
      type: "benchPress",
    },
    {
      id: 3,
      weight: 185,
      date: "2020-05-15",
      week: 3,
      type: "benchPress",
    },
    {
      id: 4,
      weight: 195,
      date: "2020-05-20",
      week: 4,
      type: "benchPress",
    },
    {
      id: 5,
      weight: 195,
      date: "2020-05-25",
      week: 5,
      type: "filler",
    },
    {
      id: 6,
      weight: 205,
      date: "2020-05-30",
      week: 6,
      type: "benchPress",
    },
    {
      id: 7,
      weight: 225,
      date: "2020-06-05",
      week: 7,
      type: "benchPress",
    },
  ],
  deadlift: [
    {
      id: 1,
      weight: 225,
      date: "2020-05-05",
      week: 1,
      type: "deadlift",
    },
    {
      id: 2,
      weight: 245,
      date: "2020-05-10",
      week: 2,
      type: "deadlift",
    },
    {
      id: 3,
      weight: 285,
      date: "2020-05-15",
      week: 3,
      type: "deadlift",
    },
    {
      id: 4,
      weight: 305,
      date: "2020-05-20",
      week: 4,
      type: "deadlift",
    },
    {
      id: 5,
      weight: 315,
      date: "2020-05-25",
      week: 5,
      type: "filler",
    },
    {
      id: 6,
      weight: 325,
      date: "2020-05-30",
      week: 6,
      type: "deadlift",
    },
    {
      id: 7,
      weight: 335,
      date: "2020-06-05",
      week: 7,
      type: "deadlift",
    },
  ],
  overheadPress: [
    {
      id: 1,
      weight: 95,
      date: "2020-05-05",
      week: 1,
      type: "overheadPress",
    },
    {
      id: 2,
      weight: 95,
      date: "2020-05-10",
      week: 2,
      type: "overheadPress",
    },
    {
      id: 3,
      weight: 105,
      date: "2020-05-15",
      week: 3,
      type: "overheadPress",
    },
    {
      id: 4,
      weight: 115,
      date: "2020-05-20",
      week: 4,
      type: "overheadPress",
    },
    {
      id: 5,
      weight: 125,
      date: "2020-05-25",
      week: 5,
      type: "overheadPress",
    },
    {
      id: 6,
      weight: 135,
      date: "2020-05-30",
      week: 6,
      type: "overheadPress",
    },
    {
      id: 7,
      weight: 135,
      date: "2020-06-05",
      week: 7,
      type: "overheadPress",
    },
  ],
  squat: [
    {
      id: 1,
      weight: 225,
      date: "2020-05-05",
      week: 1,
      type: "squat",
    },
    {
      id: 2,
      weight: 255,
      date: "2020-05-10",
      week: 2,
      type: "squat",
    },
    {
      id: 3,
      weight: 285,
      date: "2020-05-15",
      week: 3,
      type: "squat",
    },
    {
      id: 4,
      weight: 295,
      date: "2020-05-20",
      week: 4,
      type: "squat",
    },
    {
      id: 5,
      weight: 305,
      date: "2020-05-25",
      week: 5,
      type: "squat",
    },
    {
      id: 6,
      weight: 315,
      date: "2020-05-30",
      week: 6,
      type: "squat",
    },
    {
      id: 7,
      weight: 325,
      date: "2020-06-05",
      week: 7,
      type: "squat",
    },
  ],
};
